### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by cherifVN** [anonymousException/renpy-translator#10]
Hello, I wanted to try your program but I noticed that it was malicious, I had several alerts during the download. I ran it in a sandbox to minimize risks
if you don't believe me scan it on virustotal. And don't tell me it's a false positive because the number of antiviruses calling it dangerous is high

I am looking forward to hearing from you

**Comment by anonymousException** [comment]
But the fact is it's a false positive , as I mentioned in FAQ:
This program is packed by pyinstaller and with file operation (open read write) ，so may cause false detection
If you are worried about this , you can download the source code and run the program yourself
You can view the source code and pack the program , then you will get the same virus detected result

**Comment by anonymousException** [comment]
Actually I'm still trying to solve the false detection problem

**Comment by anonymousException** [comment]
Thanks for your issue , new build action : Nuitka is supported which will not cause a false positive for most antiviruses.
Already checked with https://www.virustotal.com/
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/139fa222-5333-4e36-bba2-2d1101a8ab18)
![image](https://github.com/anonymousException/renpy-translator/assets/157234942/3a4ba1f3-0b07-4db8-9077-d6f2e22a35cd)
From now on , both Nuitka and Pyinstaller version will be published to release. You can choose the one you want
Besides due to the multi-files of Nuitka Build ,  a setup version can make things easier
You can get the latest version from : [latest](https://github.com/anonymousException/renpy-translator/releases/latest)
