### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by beskep** [anonymousException/renpy-translator#40]
![image](https://github.com/user-attachments/assets/ff43b83c-dae7-44a3-bfa4-e78bf071acd2)

RenpyTranslator v2.4.5
Virus detected in Microsoft Defender and VirusTotal.

**Comment by anonymousException** [comment]
It's false positive due to different build options
You can found that, the installer version is not detected as virus : [virustotal result](https://www.virustotal.com/gui/file/110d626776383895630db993263b8cff5a7c02c60f7309d8506aa2507221b971)
![image](https://github.com/user-attachments/assets/c1bfae8f-011f-4985-bbf9-a8c1e4d805b5)


| Release Package                           | Explanation                  | Advantage                                            | Disadvantage                                             |
| ----------------------------------------- | ---------------------------- | ---------------------------------------------------- | -------------------------------------------------------- |
| RenpyTranslator-Win.Pyinstaller.Build.zip | build by Pyinstaller         | the executable file is single and light              | may cause false positive as **virus**                    |
| RenpyTranslator-Win.Nuitka.Build.zip      | build by Nuitka              | will not cause a false positive for most antiviruses | the executable file contain many extra support libraries |
| RenpyTranslatorInstaller.exe              | installer for Nuitka version | make things easier                                   | need to install and better uninstall the pre-version before install

**Comment by beskep** [comment]
Thank you for your kind response.
