### ISSUE TITLE
Incomplete extraction

### ISSUE THREAD

**Issue by jusaozzz** [anonymousException/renpy-translator#5]
Incomplete extraction

![Screenshot_1](https://github.com/anonymousException/renpy-translator/assets/155393679/f0da9bf5-0c5f-48a6-aedd-46819bb1a1f4)
![Screenshot_2](https://github.com/anonymousException/renpy-translator/assets/155393679/fb82d338-f2e3-4662-8a1e-229a844d612b)
Useiden tiedostojen epätäydellinen poiminta vain yhdellä rivillä

**Comment by anonymousException** [comment]
Are you sure the target rpy file has enough extractable contents to extract
Or can you upload the gameUI.rpy file for me to have a test
As I mentioned on the last  [FAQ](https://github.com/anonymousException/renpy-translator#other)
It depends on the original code , extraction may not completely covered if the original code is not quite translation-friendly

To avoid extra useless extraction , the extraction function in this tool will not extract sentences match the following style :

the length of sentences (space and special synbol will be counted as zero length)  lower than 8 

for example :

```
"I know [special symbol]"
```

the actual effect content is

```
Iknow
```

the length is only 5 , so it will not be extracted by the extraction from the tool

------

Besides the contents in [ConditionSwitch()](https://www.renpy.org/doc/html/displayables.html#ConditionSwitch) will also not be translated due to switch code may contained in it

**Comment by jusaozzz** [comment]
Yes

**Comment by jusaozzz** [comment]
Yeah, more than a folder. Folders can extract duplicates and cause errors. A single rpy. It's the source file that's being extracted. Not the default tl file.

**Comment by jusaozzz** [comment]
Ich bin etwas verwirrt, ob rst eine Sprachdatei oder etwas anderes ist. Die angezeigte Meldung deutete auf einen Übersetzungsfehler hin.

**Comment by jusaozzz** [comment]
Liegt es am API-Parameter oder an der Sprachdatei?

**Comment by jusaozzz** [comment]
I tried many times and couldn't add the engine properly. Do I need to clone main.py to add a new translation engine or what?
